
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: webhook-server-cert
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
